name: Run Playwright Tests

on:
  schedule:
    - cron: '0 22 * * *'  # 05:00 WIB (UTC+7)
    - cron: '0 10 * * *'  # 17:00 WIB
  workflow_dispatch:      # Bisa dijalankan manual

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run Playwright tests and send report
        run: python runall_clean.py
